#!/bin/bash

PKGDIR="/opt/demoiselle/tool/nimble/"
bindir="$PKGDIR/bin"

ln -s $bindir/demoiselle /usr/local/bin
ln -s $bindir/startDemoiselle /usr/local/bin

cp $bindir/demoiselle-completion.sh /etc/bash_completion.d/

exit 0
