#!/bin/bash

PKGDIR="./opt/demoiselle/tool/nimble-1.1.0/"

if [ ! -d $PKGDIR ]; then
	echo "Diretório não encontrado: $PKGDIR"
	exit 1
fi

bindir="$PKGDIR/bin"

#find $template -type d -exec chmod 775 {} \;
#find $template -type f -exec chmod a+r {} \;

chmod +x $bindir/*
