#!/bin/bash

PKGDIR="/opt/demoiselle/server/jboss-6.1"

if [ ! -d $PKGDIR ]; then
	echo "Diretório não encontrado: $PKGDIR"
	exit 1
fi

find $PKGDIR -type d -exec chmod 777 {} \;
find $PKGDIR -type f -exec chmod a+r,a+w {} \;

rm -rf $PKGDIR/server/default/data
rm -rf $PKGDIR/server/default/log
rm -rf $PKGDIR/server/default/tmp
rm -rf $PKGDIR/server/default/work

rm -rf $PKGDIR/bin/*.lck
rm -rf $PKGDIR/bin/*.log
#rm -rf $PKGDIR/bin/*.properties
rm -rf $PKGDIR/bin/*.script

exit 0
